spring:
  application:
    name: springboot-mbp
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.22:3306/mbp
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # redis 配置
  redis:
    port: 6379
    host: 192.168.10.22
    database: 0
    password: 123456
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 100ms
  jackson:
    default-property-inclusion: non_null  # JSON处理时忽略非空字段
server:
  port: 7529
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      select-strategy: not_empty # 入参为null时去除
snowflake:
  workerId: 1 #参数1为终端ID
  datacenterId: 1 #数据中心ID
# 系统功能
powerconfig:
  interfaceAuth: true # 开启系统接口鉴权 true | false
