
spring:
  # 应用名称
  application:
    name: springboot-mbp
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jackson:
    default-property-inclusion: non_null  # JSON处理时忽略非空字段
server:
  port: 7529
  servlet:
    context-path: /api
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      where-strategy: not_empty
      insert-strategy: not_null
      update-strategy: not_null
# 系统功能
powerconfig:
  interfaceAuth: true # 开启系统接口鉴权 true | false
  # 注意：日志功能依赖RabbitMQ
  loginLogRecords: true # 开启登录日志记录 true | false
  requestLogRecords: false # 开启请求日志记录 true | false （不建议开启，线上的请求过多）
